### ISSUE TITLE
Namespace optimization #2

### ISSUE THREAD

**Issue by eranFirelfy** [stickleprojects/VSDropAssist#23]
When dropping to a class in the same level as the entity (the controller and entity are both in folders of the same level) the full namespace is copied:
![2016-03-23_13h42_57](https://cloud.githubusercontent.com/assets/18003268/13984254/abbb3970-f0fd-11e5-856e-67058f61beeb.jpg)

**Comment by stickleprojects** [comment]
Hi - this is as expected

the namespace of the class in the editor is Northwind.DevDemo,
the object you are dropping is Northwind.Models.
You haven't got a using for Northwind.

Therefore, the full namespace is given.

There is some dispute about whether the default namespace for a project is required for variables - in my experimentation I found the default namespace was not automatically included and the code wouldn't compile - so I took it out, but i had _thought _ it should be.
I'll investigate further later tonight.

**Comment by eranFirelfy** [comment]
I appreciate your response.
As you can see from the VS2015 screen capture, even VS indicates the "Northwind" part is redundant, so it colors it Gray.

**Comment by stickleprojects** [comment]
Fair enough. I'll add it back in :)

**Comment by stickleprojects** [comment]
HI Eran

I have found another nuance, if I include the default namespace.
Northwind project
Open the Models.Suppliers class
Drag & Drop Northwind.Orders.Views.ShowOrderDetails into the Supplers class

The default namespace is "Northwind", which as per your comment above, I have removed from the class declaration, leaving "Orders.Views.ShowOrderDetails", but there is a class Models.Orders which is causing this code to not compile, because Models.Orders.Views.ShowOrderDetails doesnt exist.
Its going to be difficult to determine if this conflict will occur, so I would rather not include the default namespace and leave things a bit more explicit.
Thoughts?

**Comment by eranFirelfy** [comment]
Hi Kieron,

I understand that you found a scenario causing a conflict, I am not sure it it relevant, since there is no way in which I will drag a view into a class like this.

While we are on this subject - I was not aware that dragging a view does something at all.
I have tried it - dropping creates two lines, not one:
![2016-03-24_16h55_06](https://cloud.githubusercontent.com/assets/18003268/14020743/2f17ae1e-f1e1-11e5-87b2-b1303c7c6918.jpg)
